### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by leomelzer**
Different iteration of the README.md format in preparation for the talks listing on www.

A couple things I noticed while looking through them: 

1. Marking talks either English or German feels weird, most of the times it only marks the language of the slides, whereas the actual talk might have been given in another language (most obvious is English slides and German presentation)
2. We should accommodate for the *Video* if it is provided
3. Talk titles might be links, e.g. to open source projects

I think given our intended target group for www we don't need to explicitly split the content by language - more recent content is better.

What do you think?

### CODE REVIEW

**Comment by leomelzer** [comment]
The format validation could check the following things:

1. `<a lang="$lang"></a>`
2. Paragraph with description
3. Unordered list with the following entries
   1. Author (required)
   2. Event (required)
   3. Date (required)
   4. Slides (optional)
   5. Video (optional)

If those criteria are not satisfied, the talk will not be displayed (or possibly merging / pre-commit hook fails).

**Comment by jhnns** [comment]
Looks good 👍

Just one thing: I don't think that slides are optional, as the `talks` repository should contain the slides. What do you think? And if slides are really optional, then our script needed to cope with the situation that there is a video but no slides.

**Comment by leomelzer** [comment]
@jhnns Thinking about it there really is not a relevant scenario where we won't have slides. Even a Hochschulkurs or a Lightning Talk will have them. I marked them as `(required)` in my original comment. 

Good to merge? Then we can develop against this version of the readme.

From my point of view we should add the validator at a later stage and first build the parsing for www. It only has to be forgiving, e.g. not crash if an entry is invalid. I see it as a pre-commit hook, probably making this repo a node module and set it up as a NPM script. At some point this could be incorporated in a Jenkins build or so to trigger warnings of wrongly formatted talks in the readme. How does that sound?

**Review by jhnns — APPROVED** [review]

**Comment by jhnns** [comment]
LGTM 👍 Thanks ❤️

**Pull request merged**
