### PR TITLE
Transform to new README format

### PR DESCRIPTION
**Pull request by jhnns**
- Remove redundant "Talks" headline
- Replace <a> tags with flag emojis
- Remove markdown syntax from headlines

### CODE REVIEW

**Comment by jhnns** [comment]
@leomelzer what do you think?

**Review by leomelzer — COMMENTED** [review]
@jhnns Looks good! Thinking more about the data I believe the move towards parsing the Markdown itself makes all the sense.

However I'm not convinced with the flags in front of the talk titles. When viewed in the regular GitHub rendering (not the diff) they are quite big and at first sight I thought they could represent the country the talk was held in. 

The British flag surely is used as a way to mark English speaking content but I'm not sure it is a good one, see e.g. http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

> [...] However, often the British flag is used to represent English. Within Britain, other languages other than English are spoken — including Welsh and Scottish Gaelic. [...]

https://ux.stackexchange.com/questions/2472/how-to-graphically-represent-a-language suggests either the language name in full or "tags" with the short names like "EN" and "DE". 

What do we want to mark with the language anyways? If it's only about the language of the attached slides I'd prefer to mark the Slides link explicitly e.g. `[Slides (EN)](https://linktotalkslides.foo)`. Another option would be to record the data in the Markdown file and then refer the decision on how to render that information to the processing frontend, www in our case. There we could move the language identifier around in the view without changing the data format then.

What do you think?

**Comment by jhnns** [comment]
You're right, we should not use language emojis.

I think it's nice to have a small hint about what language the title and the description is in. It must look weird for non-German users to suddenly see a different language.

What do you think of adding a language postfix to the title, like `(DE)` if it's not english:

---
## HTTP/2

HTTP/2 is not the new kid on the block anymore, but it's still not as widely adopted as one might think. This talk is about the history of HTTP, reasons why HTTP 1.x does not work as well anymore and of course about the architecture and features of HTTP/2. 

* Michael Jaser
* [Hochschule Augsburg, Gastvorlesung Web-Technologien](http://hs-augsburg.de)
* April 12th, 2018
* [Slides](https://peerigon.github.io/talks/2018-04-12-hsa-http2/)

## App Strategie - Der Weg zur Nummer Eins (DE)

Wie erreiche ich alle Smartphone-Nutzer? Was zeichnet eine gute App aus? Wie erreiche ich ein hohes Engagement der Nutzer? Wie schaffe ich das nötige Wachstum?

* Stephan Batteiger
* [Forum Digitales Marketing, Nördlingen](http://tcw-donau-ries.de/wp-content/uploads/2018/01/Forum_Digitales-Marketing.pdf)
* March 6th, 2018
* [Slides](https://peerigon.github.io/talks/2018-03-06-app-strategie-der-weg-zur-nummer-eins/)

## JavaScript RoadTrip

Smartphone, Tablet, Desktop: Everybody uses Web applications like Spotify, Slack or Facebook every day. So why not develop an infotainment system based on open web technology? We want to share our experience gained in the developing of the Sono Motors infotainment system: What do you have to keep in mind for using it in a car? How can you implement an interface on Smartphone and Dashboard? How is it even possible to control and pilot a car with JavaScript? After this talk your dream of your own infotainment system is closer then ever!

* Michael Jaser & Jannik Keye
* [Hackerkiste 2017](https://2017.hackerkiste.de/)
* September 29th, 2017
* [Slides](https://peerigon.github.io/talks/2017-09-29-hackerkiste-javascript-roadtrip)
---

Since most talks will be on English anyway, I think it's good to have a default. I wouldn't handle the locale in the frontend then. We just display the title with the postfix as it is. I think it's still good to have the German talk on the English page because some English speaking persons do speak German :)

**Comment by leomelzer** [comment]
Looks good to me! IMHO that works well for our intended audience and is easy to implement and maintain. 

If we ever have the requirement to have the locale in a more structured way we can rethink the format - but in the end Markdown is not intended for embedding data properties so lets not try to make it behave that way :)

**Review by leomelzer — APPROVED** [review]

**Comment by jhnns** [comment]
Awesssssssome! 🎉

**Pull request merged**
